<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Disqord.Bot" Version="1.0.0-alpha5.77" />
        <PackageReference Include="FluentValidation" Version="11.11.0" />
        <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
        <PackageReference Include="Humanizer" Version="2.14.1" />
        <PackageReference Include="Prometheus.Client.AspNetCore" Version="5.0.0" />
        <PackageReference Include="Prometheus.Client.DependencyInjection" Version="1.5.1" />
        <PackageReference Include="Riok.Mapperly" Version="4.1.1" />
        <PackageReference Include="Serilog" Version="4.2.0" />
        <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
        <PackageReference Include="Serilog.Enrichers.ExceptionData" Version="1.0.0" />
        <PackageReference Include="Serilog.Exceptions" Version="8.4.0" />
        <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
        <PackageReference Include="Serilog.Sinks.PeriodicBatching" Version="5.0.0" />
        <PackageReference Include="Serilog.Sinks.PostgreSQL" Version="2.3.0" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
      <None Remove="Data\Template\ProfileTemplate.png" />
      <Content Include="Data\Template\ProfileTemplate.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Data\Template\ProfileTemplateOld.png" />
      <Content Include="Data\Template\ProfileTemplateOld.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Hanekawa.Infrastructure\Hanekawa.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Commands\Slash\Advertise\" />
      <Folder Include="Commands\Slash\AutoMessage\" />
      <Folder Include="Commands\Slash\Board\" />
      <Folder Include="Commands\Slash\Boost\" />
      <Folder Include="Extensions\" />
      <Folder Include="Validators\" />
    </ItemGroup>

    <ItemGroup>
      <None Update="Data\Template\WelcomeDefault.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Data\Fonts\ARIAL.TTF">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Data\Fonts\TIMES.TTF">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>