// <auto-generated />
using System;
using System.Collections.Generic;
using Hanekawa.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Hanekawa.Database.Migrations
{
    [DbContext(typeof(DbService))]
    [Migration("20200921211009_AutomatedMessage")]
    partial class AutomatedMessage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Hanekawa.Database.Tables.Account.Account", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ChannelVoiceTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Class")
                        .HasColumnType("integer");

                    b.Property<int>("Credit")
                        .HasColumnType("integer");

                    b.Property<int>("CreditSpecial")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DailyCredit")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Exp")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FirstMessage")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("GameKillAmount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastMessage")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MvpCount")
                        .HasColumnType("integer");

                    b.Property<bool>("MvpOptOut")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfilePic")
                        .HasColumnType("text");

                    b.Property<int>("Rep")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RepCooldown")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Sessions")
                        .HasColumnType("integer");

                    b.Property<int>("StarGiven")
                        .HasColumnType("integer");

                    b.Property<int>("StarReceived")
                        .HasColumnType("integer");

                    b.Property<long>("StatMessages")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan>("StatVoiceTime")
                        .HasColumnType("interval");

                    b.Property<int>("TotalExp")
                        .HasColumnType("integer");

                    b.Property<DateTime>("VoiceExpTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("GuildId", "UserId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Account.AccountGlobal", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("Credit")
                        .HasColumnType("integer");

                    b.Property<int>("Exp")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Rep")
                        .HasColumnType("integer");

                    b.Property<int>("StarGive")
                        .HasColumnType("integer");

                    b.Property<int>("StarReceive")
                        .HasColumnType("integer");

                    b.Property<int>("TotalExp")
                        .HasColumnType("integer");

                    b.Property<int>("UserColor")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("AccountGlobals");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Account.Highlight", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string[]>("Highlights")
                        .HasColumnType("text[]");

                    b.HasKey("GuildId", "UserId");

                    b.ToTable("Highlights");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Account.Inventory", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.HasKey("GuildId", "UserId", "ItemId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Account.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CriticalIncrease")
                        .HasColumnType("integer");

                    b.Property<int>("DamageIncrease")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("HealthIncrease")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("Role")
                        .HasColumnType("bigint");

                    b.Property<int>("Sell")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Achievement.AchievementMeta", b =>
                {
                    b.Property<int>("AchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AchievementDifficulty")
                        .HasColumnType("integer");

                    b.Property<int>("AchievementNameId")
                        .HasColumnType("integer");

                    b.Property<int?>("AchievementTypeTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("Global")
                        .HasColumnType("boolean");

                    b.Property<bool>("Hidden")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("Once")
                        .HasColumnType("boolean");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("Requirement")
                        .HasColumnType("integer");

                    b.Property<int?>("Reward")
                        .HasColumnType("integer");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("AchievementId");

                    b.HasIndex("AchievementNameId");

                    b.HasIndex("AchievementTypeTypeId");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Achievement.AchievementName", b =>
                {
                    b.Property<int>("AchievementNameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("Stackable")
                        .HasColumnType("boolean");

                    b.HasKey("AchievementNameId");

                    b.ToTable("AchievementNames");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Achievement.AchievementTracker", b =>
                {
                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.HasKey("Type", "UserId");

                    b.ToTable("AchievementTrackers");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Achievement.AchievementType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("TypeId");

                    b.ToTable("AchievementTypes");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Achievement.AchievementUnlock", b =>
                {
                    b.Property<int>("AchievementId")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("AchievementId", "UserId");

                    b.ToTable("AchievementUnlocks");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Administration.ApprovalQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UploadTimeOffset")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Uploader")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id", "GuildId");

                    b.ToTable("ApprovalQueues");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Administration.Blacklist", b =>
                {
                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<long>("ResponsibleUser")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("Unban")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GuildId");

                    b.ToTable("Blacklists");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Advertise.DblAuth", b =>
                {
                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<Guid>("AuthKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CreditGain")
                        .HasColumnType("integer");

                    b.Property<int>("ExpGain")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<long?>("RoleIdReward")
                        .HasColumnType("bigint");

                    b.Property<int>("SpecialCredit")
                        .HasColumnType("integer");

                    b.HasKey("GuildId");

                    b.ToTable("DblAuths");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Advertise.VoteLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("VoteLogs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.AutoMessage.AutoMessage", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<long>("Creator")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan>("Interval")
                        .HasColumnType("interval");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.HasKey("GuildId", "Name");

                    b.ToTable("AutoMessages");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.BoardConfig.Board", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("Boarded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StarAmount")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("GuildId", "MessageId");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.BotGame.GameClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ChanceAvoid")
                        .HasColumnType("integer");

                    b.Property<int>("ChanceCrit")
                        .HasColumnType("integer");

                    b.Property<long>("LevelRequirement")
                        .HasColumnType("bigint");

                    b.Property<double>("ModifierAvoidance")
                        .HasColumnType("double precision");

                    b.Property<double>("ModifierCriticalChance")
                        .HasColumnType("double precision");

                    b.Property<double>("ModifierDamage")
                        .HasColumnType("double precision");

                    b.Property<double>("ModifierHealth")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GameClasses");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.BotGame.GameConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("DefaultDamage")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultHealth")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GameConfigs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.BotGame.GameEnemy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int>("CreditGain")
                        .HasColumnType("integer");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<bool>("Elite")
                        .HasColumnType("boolean");

                    b.Property<int>("ExpGain")
                        .HasColumnType("integer");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("Rare")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("GameEnemies");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Club.ClubBlacklist", b =>
                {
                    b.Property<int>("ClubId")
                        .HasColumnType("integer");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("BlackListUser")
                        .HasColumnType("bigint");

                    b.Property<long>("IssuedUser")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClubId", "GuildId", "BlackListUser");

                    b.ToTable("ClubBlacklists");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Club.ClubInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long?>("AdMessage")
                        .HasColumnType("bigint");

                    b.Property<bool>("AutoAdd")
                        .HasColumnType("boolean");

                    b.Property<long?>("Channel")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<long>("LeaderId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("Public")
                        .HasColumnType("boolean");

                    b.Property<long?>("Role")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ClubInfos");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Club.ClubUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ClubId")
                        .HasColumnType("integer");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("JoinDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ClubPlayers");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.EventPayout", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.HasKey("GuildId", "UserId");

                    b.ToTable("EventPayouts");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.Guild.AdminConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int?>("EmoteCountFilter")
                        .HasColumnType("integer");

                    b.Property<bool>("FilterAllInv")
                        .HasColumnType("boolean");

                    b.Property<bool>("FilterInvites")
                        .HasColumnType("boolean");

                    b.Property<int?>("FilterMsgLength")
                        .HasColumnType("integer");

                    b.Property<bool>("FilterUrls")
                        .HasColumnType("boolean");

                    b.Property<bool>("IgnoreAllChannels")
                        .HasColumnType("boolean");

                    b.Property<int?>("MentionCountFilter")
                        .HasColumnType("integer");

                    b.Property<long?>("MuteRole")
                        .HasColumnType("bigint");

                    b.HasKey("GuildId");

                    b.ToTable("AdminConfigs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.Guild.BoardConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("Channel")
                        .HasColumnType("bigint");

                    b.Property<string>("Emote")
                        .HasColumnType("text");

                    b.HasKey("GuildId");

                    b.ToTable("BoardConfigs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.Guild.BoostConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<int>("CreditGain")
                        .HasColumnType("integer");

                    b.Property<int>("ExpGain")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<int>("SpecialCreditGain")
                        .HasColumnType("integer");

                    b.HasKey("GuildId");

                    b.ToTable("BoostConfigs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.Guild.ChannelConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("DesignChannel")
                        .HasColumnType("bigint");

                    b.Property<long?>("EventChannel")
                        .HasColumnType("bigint");

                    b.Property<long?>("EventSchedulerChannel")
                        .HasColumnType("bigint");

                    b.Property<long?>("ModChannel")
                        .HasColumnType("bigint");

                    b.Property<long?>("QuestionAndAnswerChannel")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReportChannel")
                        .HasColumnType("bigint");

                    b.Property<long?>("SelfAssignableChannel")
                        .HasColumnType("bigint");

                    b.Property<long[]>("SelfAssignableMessages")
                        .HasColumnType("bigint[]");

                    b.HasKey("GuildId");

                    b.ToTable("ChannelConfigs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.Guild.ClubConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("AdvertisementChannel")
                        .HasColumnType("bigint");

                    b.Property<bool>("AutoPrune")
                        .HasColumnType("boolean");

                    b.Property<long?>("ChannelCategory")
                        .HasColumnType("bigint");

                    b.Property<int>("ChannelRequiredAmount")
                        .HasColumnType("integer");

                    b.Property<int>("ChannelRequiredLevel")
                        .HasColumnType("integer");

                    b.Property<bool>("EnableVoiceChannel")
                        .HasColumnType("boolean");

                    b.Property<bool>("RoleEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("GuildId");

                    b.ToTable("ClubConfigs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.Guild.CurrencyConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CurrencyName")
                        .HasColumnType("text");

                    b.Property<string>("CurrencySign")
                        .HasColumnType("text");

                    b.Property<bool>("EmoteCurrency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("SpecialCurrencyName")
                        .HasColumnType("text");

                    b.Property<string>("SpecialCurrencySign")
                        .HasColumnType("text");

                    b.Property<bool>("SpecialEmoteCurrency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("GuildId");

                    b.ToTable("CurrencyConfigs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.Guild.DropConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Emote")
                        .HasColumnType("text");

                    b.HasKey("GuildId");

                    b.ToTable("DropConfigs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.Guild.LevelConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<double>("BoostExpMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(1.0);

                    b.Property<bool>("ExpDisabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("StackLvlRoles")
                        .HasColumnType("boolean");

                    b.Property<bool>("TextExpEnabled")
                        .HasColumnType("boolean");

                    b.Property<double>("TextExpMultiplier")
                        .HasColumnType("double precision");

                    b.Property<bool>("VoiceExpEnabled")
                        .HasColumnType("boolean");

                    b.Property<double>("VoiceExpMultiplier")
                        .HasColumnType("double precision");

                    b.HasKey("GuildId");

                    b.ToTable("LevelConfigs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.Guild.LoggingConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("LogAutoMod")
                        .HasColumnType("bigint");

                    b.Property<long?>("LogAvi")
                        .HasColumnType("bigint");

                    b.Property<long?>("LogBan")
                        .HasColumnType("bigint");

                    b.Property<long?>("LogJoin")
                        .HasColumnType("bigint");

                    b.Property<long?>("LogMsg")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("LogVoice")
                        .HasColumnType("numeric(20,0)");

                    b.Property<long?>("LogWarn")
                        .HasColumnType("bigint");

                    b.HasKey("GuildId");

                    b.ToTable("LoggingConfigs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.Guild.SuggestionConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("Channel")
                        .HasColumnType("bigint");

                    b.Property<string>("EmoteNo")
                        .HasColumnType("text");

                    b.Property<string>("EmoteYes")
                        .HasColumnType("text");

                    b.HasKey("GuildId");

                    b.ToTable("SuggestionConfigs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.Guild.WelcomeConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("AutoDelOnLeave")
                        .HasColumnType("boolean");

                    b.Property<bool>("Banner")
                        .HasColumnType("boolean");

                    b.Property<long?>("Channel")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("IgnoreNew")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Limit")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<int?>("Reward")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("TimeToDelete")
                        .HasColumnType("interval");

                    b.HasKey("GuildId");

                    b.ToTable("WelcomeConfigs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.GuildConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("AnimeAirChannel")
                        .HasColumnType("bigint");

                    b.Property<bool>("AutomaticEventSchedule")
                        .HasColumnType("boolean");

                    b.Property<int>("EmbedColor")
                        .HasColumnType("integer");

                    b.Property<long?>("HungerGameChannel")
                        .HasColumnType("bigint");

                    b.Property<long?>("MusicChannel")
                        .HasColumnType("bigint");

                    b.Property<long?>("MusicVcChannel")
                        .HasColumnType("bigint");

                    b.Property<long?>("MvpChannel")
                        .HasColumnType("bigint");

                    b.Property<string>("Prefix")
                        .HasColumnType("text");

                    b.Property<bool>("Premium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("GuildId");

                    b.ToTable("GuildConfigs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.IgnoreChannel", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.HasKey("GuildId", "ChannelId");

                    b.ToTable("IgnoreChannels");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.LevelExpEvent", b =>
                {
                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<double>("Multiplier")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("GuildId");

                    b.ToTable("LevelExpEvents");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.LevelExpReduction", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GuildId", "ChannelId");

                    b.ToTable("LevelExpReductions");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.LevelReward", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<long>("Role")
                        .HasColumnType("bigint");

                    b.Property<bool>("Stackable")
                        .HasColumnType("boolean");

                    b.HasKey("GuildId", "Level");

                    b.ToTable("LevelRewards");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.LootChannel", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.HasKey("GuildId", "ChannelId");

                    b.ToTable("LootChannels");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.SelfAssignAbleRole", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("EmoteMessageFormat")
                        .HasColumnType("text");

                    b.Property<string>("EmoteReactFormat")
                        .HasColumnType("text");

                    b.Property<bool>("Exclusive")
                        .HasColumnType("boolean");

                    b.HasKey("GuildId", "RoleId");

                    b.ToTable("SelfAssignAbleRoles");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.WelcomeBanner", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("IsNsfw")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UploadTimeOffset")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Uploader")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("GuildId", "Id");

                    b.ToTable("WelcomeBanners");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Internal.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CallSite")
                        .HasColumnType("text");

                    b.Property<string>("Exception")
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<string>("Logger")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("TimeStamp")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Moderation.ModLog", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ModId")
                        .HasColumnType("bigint");

                    b.Property<string>("Response")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id", "GuildId");

                    b.ToTable("ModLogs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Moderation.MuteTimer", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("UserId", "GuildId");

                    b.ToTable("MuteTimers");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Moderation.Report", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("Attachment")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<long?>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id", "GuildId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Moderation.Suggestion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Response")
                        .HasColumnType("text");

                    b.Property<long?>("ResponseUser")
                        .HasColumnType("bigint");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id", "GuildId");

                    b.ToTable("Suggestions");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Moderation.Warn", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Moderator")
                        .HasColumnType("numeric(20,0)");

                    b.Property<TimeSpan?>("MuteTimer")
                        .HasColumnType("interval");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Valid")
                        .HasColumnType("boolean");

                    b.HasKey("Id", "GuildId");

                    b.ToTable("Warns");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Music.MusicConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("TextChId")
                        .HasColumnType("bigint");

                    b.Property<long?>("VoiceChId")
                        .HasColumnType("bigint");

                    b.HasKey("GuildId");

                    b.ToTable("MusicConfigs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Music.Playlist", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<List<string>>("Songs")
                        .HasColumnType("text[]");

                    b.HasKey("GuildId", "Name");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Premium.MvpConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Disabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<long?>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("GuildId");

                    b.ToTable("MvpConfigs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Profile.Background", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("BackgroundUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Backgrounds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackgroundUrl = "https://i.imgur.com/epIb29P.png"
                        },
                        new
                        {
                            Id = 2,
                            BackgroundUrl = "https://i.imgur.com/04PbzvT.png"
                        },
                        new
                        {
                            Id = 3,
                            BackgroundUrl = "https://i.imgur.com/5ojmh76.png"
                        },
                        new
                        {
                            Id = 4,
                            BackgroundUrl = "https://i.imgur.com/OAMpNDh.png"
                        },
                        new
                        {
                            Id = 5,
                            BackgroundUrl = "https://i.imgur.com/KXO5bx5.png"
                        },
                        new
                        {
                            Id = 6,
                            BackgroundUrl = "https://i.imgur.com/5h5zZ7C.png"
                        });
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Stores.ServerStore", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<bool>("SpecialCredit")
                        .HasColumnType("boolean");

                    b.HasKey("GuildId", "RoleId");

                    b.ToTable("ServerStores");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.VoiceRoles", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("VoiceId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("GuildId", "VoiceId");

                    b.ToTable("VoiceRoles");
                });

            modelBuilder.Entity("Hanekawa.HungerGames.Entity.GameHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("Winner")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("GameHistory");
                });

            modelBuilder.Entity("Hanekawa.HungerGames.Entity.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<decimal>("UserGuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserGuildId", "UserId");

                    b.ToTable("HgInventories");
                });

            modelBuilder.Entity("Hanekawa.HungerGames.Entity.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Ammo")
                        .HasColumnType("integer");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<bool>("BleedEffect")
                        .HasColumnType("boolean");

                    b.Property<int>("GiveOrTake")
                        .HasColumnType("integer");

                    b.Property<bool>("HealOverTime")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HgItems");
                });

            modelBuilder.Entity("Hanekawa.HungerGames.Entity.Participant", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("Alive")
                        .HasColumnType("boolean");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<bool>("Bleeding")
                        .HasColumnType("boolean");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<int>("Hunger")
                        .HasColumnType("integer");

                    b.Property<int>("LatestMove")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Stamina")
                        .HasColumnType("integer");

                    b.Property<int>("Thirst")
                        .HasColumnType("integer");

                    b.Property<int>("Tiredness")
                        .HasColumnType("integer");

                    b.HasKey("GuildId", "UserId");

                    b.ToTable("HgParticipants");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Achievement.AchievementMeta", b =>
                {
                    b.HasOne("Hanekawa.Database.Tables.Achievement.AchievementName", "AchievementName")
                        .WithMany()
                        .HasForeignKey("AchievementNameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hanekawa.Database.Tables.Achievement.AchievementType", "AchievementType")
                        .WithMany()
                        .HasForeignKey("AchievementTypeTypeId");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Achievement.AchievementUnlock", b =>
                {
                    b.HasOne("Hanekawa.Database.Tables.Achievement.AchievementMeta", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hanekawa.HungerGames.Entity.Inventory", b =>
                {
                    b.HasOne("Hanekawa.HungerGames.Entity.Item", "Item")
                        .WithMany("Inventories")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hanekawa.HungerGames.Entity.Participant", "User")
                        .WithMany("Inventory")
                        .HasForeignKey("UserGuildId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
