// <auto-generated />
using System;
using System.Collections.Generic;
using Hanekawa.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Hanekawa.Database.Migrations
{
    [DbContext(typeof(DbService))]
    [Migration("20210430203020_InitialAddFour")]
    partial class InitialAddFour
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Hanekawa.Database.Tables.Account.Account", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ChannelVoiceTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Class")
                        .HasColumnType("integer");

                    b.Property<int>("Credit")
                        .HasColumnType("integer");

                    b.Property<int>("CreditSpecial")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DailyCredit")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Decay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<long>("DropClaims")
                        .HasColumnType("bigint");

                    b.Property<int>("Exp")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FirstMessage")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("GameKillAmount")
                        .HasColumnType("integer");

                    b.Property<int>("GamePvPAmount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastMessage")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MvpCount")
                        .HasColumnType("integer");

                    b.Property<bool>("MvpOptOut")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfilePic")
                        .HasColumnType("text");

                    b.Property<int>("Rep")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RepCooldown")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Sessions")
                        .HasColumnType("integer");

                    b.Property<int>("StarGiven")
                        .HasColumnType("integer");

                    b.Property<int>("StarReceived")
                        .HasColumnType("integer");

                    b.Property<long>("StatMessages")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan>("StatVoiceTime")
                        .HasColumnType("interval");

                    b.Property<int>("TotalExp")
                        .HasColumnType("integer");

                    b.Property<DateTime>("VoiceExpTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("GuildId", "UserId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Account.AccountGlobal", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Credit")
                        .HasColumnType("integer");

                    b.Property<int>("Exp")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Rep")
                        .HasColumnType("integer");

                    b.Property<int>("StarGive")
                        .HasColumnType("integer");

                    b.Property<int>("StarReceive")
                        .HasColumnType("integer");

                    b.Property<int>("TotalExp")
                        .HasColumnType("integer");

                    b.Property<int>("UserColor")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("AccountGlobals");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Account.Achievement.Achievement", b =>
                {
                    b.Property<Guid>("AchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<bool>("Hidden")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("Requirement")
                        .HasColumnType("integer");

                    b.Property<int?>("Reward")
                        .HasColumnType("integer");

                    b.HasKey("AchievementId");

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            AchievementId = new Guid("35c0c55e-1624-496e-80e3-6b749bce7ec9"),
                            Category = 0,
                            Description = "Reach Server Level 5",
                            Difficulty = 0,
                            Hidden = false,
                            ImageUrl = "",
                            Name = "Level 5",
                            Points = 10,
                            Requirement = 5
                        },
                        new
                        {
                            AchievementId = new Guid("cf99b550-9f40-4fae-af4f-d752c623764a"),
                            Category = 0,
                            Description = "Reach Server Level 10",
                            Difficulty = 0,
                            Hidden = false,
                            ImageUrl = "",
                            Name = "Level 10",
                            Points = 10,
                            Requirement = 10
                        },
                        new
                        {
                            AchievementId = new Guid("52394c8d-f480-415e-94b8-705cd5785c41"),
                            Category = 0,
                            Description = "Reach Server Level 20",
                            Difficulty = 0,
                            Hidden = false,
                            ImageUrl = "",
                            Name = "Level 20",
                            Points = 10,
                            Requirement = 20
                        },
                        new
                        {
                            AchievementId = new Guid("9a8ab7a7-d522-402f-af50-92fa9abad84f"),
                            Category = 0,
                            Description = "Reach Server Level 30",
                            Difficulty = 0,
                            Hidden = false,
                            ImageUrl = "",
                            Name = "Level 30",
                            Points = 10,
                            Requirement = 30
                        },
                        new
                        {
                            AchievementId = new Guid("fd0261d9-5590-4dfd-ac44-d5b4ecd7f249"),
                            Category = 0,
                            Description = "Reach Server Level 40",
                            Difficulty = 0,
                            Hidden = false,
                            ImageUrl = "",
                            Name = "Level 40",
                            Points = 10,
                            Requirement = 40
                        },
                        new
                        {
                            AchievementId = new Guid("4bd811cc-f752-4c3c-85a3-ed49e410f88e"),
                            Category = 0,
                            Description = "Reach Server Level 50",
                            Difficulty = 1,
                            Hidden = false,
                            ImageUrl = "",
                            Name = "Level 50",
                            Points = 10,
                            Requirement = 50
                        },
                        new
                        {
                            AchievementId = new Guid("c909b440-8777-4dc7-82e8-ea0f0255b3a3"),
                            Category = 0,
                            Description = "Reach Server Level 60",
                            Difficulty = 1,
                            Hidden = false,
                            ImageUrl = "",
                            Name = "Level 60",
                            Points = 10,
                            Requirement = 60
                        },
                        new
                        {
                            AchievementId = new Guid("44f7cfc4-4d23-44f8-8d21-09b5daad169d"),
                            Category = 0,
                            Description = "Reach Server Level 70",
                            Difficulty = 2,
                            Hidden = false,
                            ImageUrl = "",
                            Name = "Reach Server Level 70",
                            Points = 10,
                            Requirement = 70
                        },
                        new
                        {
                            AchievementId = new Guid("c8612766-f919-4d35-abaa-10078baa7da3"),
                            Category = 0,
                            Description = "Reach Server Level 80",
                            Difficulty = 2,
                            Hidden = false,
                            ImageUrl = "",
                            Name = "Level 80",
                            Points = 10,
                            Requirement = 80
                        },
                        new
                        {
                            AchievementId = new Guid("f67f05d9-6424-4eeb-b5e8-c16811cbea64"),
                            Category = 0,
                            Description = "Reach Server Level 90",
                            Difficulty = 3,
                            Hidden = false,
                            ImageUrl = "",
                            Name = "Level 90",
                            Points = 10,
                            Requirement = 90
                        },
                        new
                        {
                            AchievementId = new Guid("bb923ced-e792-4c72-aff0-667beb7f0b3d"),
                            Category = 0,
                            Description = "Reach Server Level 100",
                            Difficulty = 3,
                            Hidden = false,
                            ImageUrl = "",
                            Name = "Level 100",
                            Points = 10,
                            Requirement = 100
                        });
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Account.Achievement.AchievementUnlocked", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("AccountUserId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("AchieveId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AchievementId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AccountUserId");

                    b.HasIndex("AchievementId");

                    b.ToTable("AchievementUnlocks");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Account.Highlight", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<List<string>>("Keywords")
                        .HasColumnType("text[]");

                    b.HasKey("GuildId", "UserId");

                    b.ToTable("Highlights");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Account.HungerGame.HungerGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Alive")
                        .HasColumnType("integer");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("Participants")
                        .HasColumnType("integer");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("HungerGames");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Account.HungerGame.HungerGameCustomChar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id", "GuildId");

                    b.ToTable("HungerGameCustomChars");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Account.HungerGame.HungerGameDefault", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HungerGameDefaults");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Avatar = "https://i.imgur.com/XMjW8Qn.png",
                            Name = "Dia"
                        },
                        new
                        {
                            Id = 2L,
                            Avatar = "https://i.imgur.com/7URjbvT.png",
                            Name = "Kanan"
                        },
                        new
                        {
                            Id = 3L,
                            Avatar = "https://i.imgur.com/tPDON9P.png",
                            Name = "Yoshiko"
                        },
                        new
                        {
                            Id = 4L,
                            Avatar = "https://i.imgur.com/dcB1loo.png",
                            Name = "Kongou"
                        },
                        new
                        {
                            Id = 5L,
                            Avatar = "https://i.imgur.com/7GC7FvJ.png",
                            Name = "Haruna"
                        },
                        new
                        {
                            Id = 6L,
                            Avatar = "https://i.imgur.com/8748bUL.png",
                            Name = "Yamato"
                        },
                        new
                        {
                            Id = 7L,
                            Avatar = "https://i.imgur.com/VLsezdF.png",
                            Name = "Akagi"
                        },
                        new
                        {
                            Id = 8L,
                            Avatar = "https://i.imgur.com/eyt9k8E.png",
                            Name = "Kaga"
                        },
                        new
                        {
                            Id = 9L,
                            Avatar = "https://i.imgur.com/4XYg6ch.png",
                            Name = "Zero Two"
                        },
                        new
                        {
                            Id = 10L,
                            Avatar = "https://i.imgur.com/Nl6WsbP.png",
                            Name = "Echidna"
                        },
                        new
                        {
                            Id = 11L,
                            Avatar = "https://i.imgur.com/kF9b4SJ.png",
                            Name = "Emilia"
                        },
                        new
                        {
                            Id = 12L,
                            Avatar = "https://i.imgur.com/y3bb8Sk.png",
                            Name = "Rem"
                        },
                        new
                        {
                            Id = 13L,
                            Avatar = "https://i.imgur.com/5CcdVBE.png",
                            Name = "Ram"
                        },
                        new
                        {
                            Id = 14L,
                            Avatar = "https://i.imgur.com/0VYBYEg.png",
                            Name = "Gura"
                        },
                        new
                        {
                            Id = 15L,
                            Avatar = "https://i.imgur.com/rYa5iYc.png",
                            Name = "Shiki"
                        },
                        new
                        {
                            Id = 16L,
                            Avatar = "https://i.imgur.com/PT8SsVB.png",
                            Name = "Chika"
                        },
                        new
                        {
                            Id = 17L,
                            Avatar = "https://i.imgur.com/5xR0ImK.png",
                            Name = "Sora"
                        },
                        new
                        {
                            Id = 18L,
                            Avatar = "https://i.imgur.com/U0NlfJd.png",
                            Name = "Nobuna"
                        },
                        new
                        {
                            Id = 19L,
                            Avatar = "https://i.imgur.com/CI9Osi5.png",
                            Name = "Akame"
                        },
                        new
                        {
                            Id = 20L,
                            Avatar = "https://i.imgur.com/GhSG97V.png",
                            Name = "Shiina"
                        },
                        new
                        {
                            Id = 21L,
                            Avatar = "https://i.imgur.com/VyJf95i.png",
                            Name = "Bocchi"
                        },
                        new
                        {
                            Id = 22L,
                            Avatar = "https://i.imgur.com/bv5ao8Z.png",
                            Name = "Enterprise"
                        },
                        new
                        {
                            Id = 23L,
                            Avatar = "https://i.imgur.com/HoNwKi9.png",
                            Name = "Chocola"
                        },
                        new
                        {
                            Id = 24L,
                            Avatar = "https://i.imgur.com/aijxHla.png",
                            Name = "Vanilla"
                        },
                        new
                        {
                            Id = 25L,
                            Avatar = "https://i.imgur.com/Wxhd5WY.png",
                            Name = "Shiro"
                        });
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Account.HungerGame.HungerGameHistory", b =>
                {
                    b.Property<Guid>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CreditReward")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExpReward")
                        .HasColumnType("integer");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("SpecialCreditReward")
                        .HasColumnType("integer");

                    b.Property<long>("Winner")
                        .HasColumnType("bigint");

                    b.HasKey("GameId");

                    b.ToTable("HungerGameHistories");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Account.HungerGame.HungerGameProfile", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Alive")
                        .HasColumnType("boolean");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<bool>("Bleeding")
                        .HasColumnType("boolean");

                    b.Property<bool>("Bot")
                        .HasColumnType("boolean");

                    b.Property<int>("Bullets")
                        .HasColumnType("integer");

                    b.Property<int>("FirstAid")
                        .HasColumnType("integer");

                    b.Property<int>("Food")
                        .HasColumnType("integer");

                    b.Property<double>("Health")
                        .HasColumnType("double precision");

                    b.Property<double>("Hunger")
                        .HasColumnType("double precision");

                    b.Property<int>("MeleeWeapon")
                        .HasColumnType("integer");

                    b.Property<int>("Move")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("RangeWeapon")
                        .HasColumnType("integer");

                    b.Property<double>("Stamina")
                        .HasColumnType("double precision");

                    b.Property<double>("Thirst")
                        .HasColumnType("double precision");

                    b.Property<double>("Tiredness")
                        .HasColumnType("double precision");

                    b.Property<int>("Water")
                        .HasColumnType("integer");

                    b.Property<int>("Weapons")
                        .HasColumnType("integer");

                    b.HasKey("GuildId", "UserId");

                    b.ToTable("HungerGameProfiles");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Account.HungerGame.HungerGameStatus", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("CreditReward")
                        .HasColumnType("integer");

                    b.Property<string>("EmoteMessageFormat")
                        .HasColumnType("text");

                    b.Property<long?>("EventChannel")
                        .HasColumnType("bigint");

                    b.Property<int>("ExpReward")
                        .HasColumnType("integer");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("uuid");

                    b.Property<long?>("RoleReward")
                        .HasColumnType("bigint");

                    b.Property<long?>("SignUpChannel")
                        .HasColumnType("bigint");

                    b.Property<string>("SignUpMessage")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SignUpStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SpecialCreditReward")
                        .HasColumnType("integer");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.HasKey("GuildId");

                    b.ToTable("HungerGameStatus");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Account.Inventory", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.HasKey("GuildId", "UserId", "ItemId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Account.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CriticalIncrease")
                        .HasColumnType("integer");

                    b.Property<int>("DamageIncrease")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("HealthIncrease")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("Role")
                        .HasColumnType("bigint");

                    b.Property<int>("Sell")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Account.Profile.Background", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BackgroundUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Backgrounds");

                    b.HasData(
                        new
                        {
                            Id = new Guid("26ca7657-c60f-4fe0-9f15-807fcd506e43"),
                            BackgroundUrl = "https://i.imgur.com/epIb29P.png"
                        },
                        new
                        {
                            Id = new Guid("be1dc76c-23a9-4284-be37-dee68f957129"),
                            BackgroundUrl = "https://i.imgur.com/04PbzvT.png"
                        },
                        new
                        {
                            Id = new Guid("2787c44e-acfb-444a-ac38-beb72ad44919"),
                            BackgroundUrl = "https://i.imgur.com/5ojmh76.png"
                        },
                        new
                        {
                            Id = new Guid("95d9c246-6def-46f0-a8f7-f749a92b4c33"),
                            BackgroundUrl = "https://i.imgur.com/OAMpNDh.png"
                        },
                        new
                        {
                            Id = new Guid("16924135-5103-42ed-8ce3-fca4a61bb179"),
                            BackgroundUrl = "https://i.imgur.com/KXO5bx5.png"
                        },
                        new
                        {
                            Id = new Guid("39d2e876-de8d-4e76-a004-c373a0ffbb3e"),
                            BackgroundUrl = "https://i.imgur.com/5h5zZ7C.png"
                        });
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Account.ShipGame.GameClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChanceAvoid")
                        .HasColumnType("integer");

                    b.Property<int>("ChanceCrit")
                        .HasColumnType("integer");

                    b.Property<int>("LevelRequirement")
                        .HasColumnType("integer");

                    b.Property<double>("ModifierAvoidance")
                        .HasColumnType("double precision");

                    b.Property<double>("ModifierCriticalChance")
                        .HasColumnType("double precision");

                    b.Property<double>("ModifierDamage")
                        .HasColumnType("double precision");

                    b.Property<double>("ModifierHealth")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GameClasses");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Account.ShipGame.GameConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DefaultDamage")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultHealth")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GameConfigs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Account.ShipGame.GameEnemy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int>("CreditGain")
                        .HasColumnType("integer");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<bool>("Elite")
                        .HasColumnType("boolean");

                    b.Property<int>("ExpGain")
                        .HasColumnType("integer");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("Rare")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("GameEnemies");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Account.Stores.ServerStore", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<bool>("SpecialCredit")
                        .HasColumnType("boolean");

                    b.HasKey("GuildId", "RoleId");

                    b.ToTable("ServerStores");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Administration.ApprovalQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UploadTimeOffset")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Uploader")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id", "GuildId");

                    b.ToTable("ApprovalQueues");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Administration.Blacklist", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<long>("ResponsibleUser")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("Unban")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GuildId");

                    b.ToTable("Blacklists");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Advertise.DblAuth", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("AuthKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CreditGain")
                        .HasColumnType("integer");

                    b.Property<int>("ExpGain")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<long?>("RoleIdReward")
                        .HasColumnType("bigint");

                    b.Property<int>("SpecialCredit")
                        .HasColumnType("integer");

                    b.HasKey("GuildId");

                    b.ToTable("DblAuths");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Advertise.VoteLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("VoteLogs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.AutoMessage.AutoMessage", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<long>("Creator")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan>("Interval")
                        .HasColumnType("interval");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.HasKey("GuildId", "Name");

                    b.ToTable("AutoMessages");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.BoardConfig.Board", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("Boarded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StarAmount")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("GuildId", "MessageId");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Club.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("AdMessage")
                        .HasColumnType("bigint");

                    b.Property<bool>("AutoAdd")
                        .HasColumnType("boolean");

                    b.Property<long?>("Channel")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<long>("Leader")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("Public")
                        .HasColumnType("boolean");

                    b.Property<long?>("Role")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ClubInfos");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Club.ClubBlacklist", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("User")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<long>("Issuer")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GuildId", "User");

                    b.HasIndex("ClubId");

                    b.ToTable("ClubBlacklists");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Club.ClubUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("ClubPlayers");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.EventPayout", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.HasKey("GuildId", "UserId");

                    b.ToTable("EventPayouts");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.Guild.AdminConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int?>("EmoteCountFilter")
                        .HasColumnType("integer");

                    b.Property<bool>("FilterAllInv")
                        .HasColumnType("boolean");

                    b.Property<bool>("FilterInvites")
                        .HasColumnType("boolean");

                    b.Property<int?>("FilterMsgLength")
                        .HasColumnType("integer");

                    b.Property<bool>("FilterUrls")
                        .HasColumnType("boolean");

                    b.Property<bool>("IgnoreAllChannels")
                        .HasColumnType("boolean");

                    b.Property<int?>("MentionCountFilter")
                        .HasColumnType("integer");

                    b.Property<long?>("MuteRole")
                        .HasColumnType("bigint");

                    b.HasKey("GuildId");

                    b.ToTable("AdminConfigs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.Guild.BoardConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long?>("Channel")
                        .HasColumnType("bigint");

                    b.Property<string>("Emote")
                        .HasColumnType("text");

                    b.HasKey("GuildId");

                    b.ToTable("BoardConfigs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.Guild.BoostConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<int>("CreditGain")
                        .HasColumnType("integer");

                    b.Property<int>("ExpGain")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<int>("SpecialCreditGain")
                        .HasColumnType("integer");

                    b.HasKey("GuildId");

                    b.ToTable("BoostConfigs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.Guild.ChannelConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DesignChannel")
                        .HasColumnType("bigint");

                    b.Property<long?>("EventChannel")
                        .HasColumnType("bigint");

                    b.Property<long?>("EventSchedulerChannel")
                        .HasColumnType("bigint");

                    b.Property<long?>("ModChannel")
                        .HasColumnType("bigint");

                    b.Property<long?>("QuestionAndAnswerChannel")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReportChannel")
                        .HasColumnType("bigint");

                    b.Property<long?>("SelfAssignableChannel")
                        .HasColumnType("bigint");

                    b.HasKey("GuildId");

                    b.ToTable("ChannelConfigs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.Guild.ClubConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long?>("AdvertisementChannel")
                        .HasColumnType("bigint");

                    b.Property<bool>("AutoPrune")
                        .HasColumnType("boolean");

                    b.Property<long?>("ChannelCategory")
                        .HasColumnType("bigint");

                    b.Property<int>("ChannelRequiredAmount")
                        .HasColumnType("integer");

                    b.Property<int>("ChannelRequiredLevel")
                        .HasColumnType("integer");

                    b.Property<bool>("EnableTextChannel")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableVoiceChannel")
                        .HasColumnType("boolean");

                    b.Property<bool>("RoleEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("GuildId");

                    b.ToTable("ClubConfigs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.Guild.CurrencyConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("CurrencyName")
                        .HasColumnType("text");

                    b.Property<string>("CurrencySign")
                        .HasColumnType("text");

                    b.Property<long?>("CurrencySignId")
                        .HasColumnType("bigint");

                    b.Property<bool>("EmoteCurrency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("SpecialCurrencyName")
                        .HasColumnType("text");

                    b.Property<string>("SpecialCurrencySign")
                        .HasColumnType("text");

                    b.Property<long?>("SpecialCurrencySignId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SpecialEmoteCurrency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("GuildId");

                    b.ToTable("CurrencyConfigs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.Guild.DropConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("Emote")
                        .HasColumnType("text");

                    b.HasKey("GuildId");

                    b.ToTable("DropConfigs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.Guild.LevelConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<double>("BoostExpMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(1.0);

                    b.Property<bool>("Decay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("ExpDisabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("StackLvlRoles")
                        .HasColumnType("boolean");

                    b.Property<bool>("TextExpEnabled")
                        .HasColumnType("boolean");

                    b.Property<double>("TextExpMultiplier")
                        .HasColumnType("double precision");

                    b.Property<bool>("VoiceExpEnabled")
                        .HasColumnType("boolean");

                    b.Property<double>("VoiceExpMultiplier")
                        .HasColumnType("double precision");

                    b.HasKey("GuildId");

                    b.ToTable("LevelConfigs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.Guild.LoggingConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LogAutoMod")
                        .HasColumnType("bigint");

                    b.Property<long?>("LogAvi")
                        .HasColumnType("bigint");

                    b.Property<long?>("LogBan")
                        .HasColumnType("bigint");

                    b.Property<long?>("LogJoin")
                        .HasColumnType("bigint");

                    b.Property<long?>("LogMsg")
                        .HasColumnType("bigint");

                    b.Property<long?>("LogReaction")
                        .HasColumnType("bigint");

                    b.Property<long?>("LogVoice")
                        .HasColumnType("bigint");

                    b.Property<long?>("LogWarn")
                        .HasColumnType("bigint");

                    b.Property<string>("ReactionWebhook")
                        .HasColumnType("text");

                    b.HasKey("GuildId");

                    b.ToTable("LoggingConfigs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.Guild.SuggestionConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long?>("Channel")
                        .HasColumnType("bigint");

                    b.Property<string>("EmoteNo")
                        .HasColumnType("text");

                    b.Property<string>("EmoteYes")
                        .HasColumnType("text");

                    b.HasKey("GuildId");

                    b.ToTable("SuggestionConfigs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.Guild.WelcomeConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<bool>("AutoDelOnLeave")
                        .HasColumnType("boolean");

                    b.Property<bool>("Banner")
                        .HasColumnType("boolean");

                    b.Property<long?>("Channel")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("IgnoreNew")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Limit")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<int?>("Reward")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("TimeToDelete")
                        .HasColumnType("interval");

                    b.HasKey("GuildId");

                    b.ToTable("WelcomeConfigs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.GuildConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("EmbedColor")
                        .HasColumnType("integer");

                    b.Property<long?>("MvpChannel")
                        .HasColumnType("bigint");

                    b.Property<string>("Prefix")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Premium")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GuildId");

                    b.ToTable("GuildConfigs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.IgnoreChannel", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.HasKey("GuildId", "ChannelId");

                    b.ToTable("IgnoreChannels");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.LevelExpEvent", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<double>("Multiplier")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("GuildId");

                    b.ToTable("LevelExpEvents");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.LevelExpReduction", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.HasKey("GuildId", "ChannelId");

                    b.ToTable("LevelExpReductions");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.LevelReward", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<bool>("NoDecay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<long>("Role")
                        .HasColumnType("bigint");

                    b.Property<bool>("Stackable")
                        .HasColumnType("boolean");

                    b.HasKey("GuildId", "Level");

                    b.ToTable("LevelRewards");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.LootChannel", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.HasKey("GuildId", "ChannelId");

                    b.ToTable("LootChannels");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.SelfAssignAbleRole", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EmoteId")
                        .HasColumnType("bigint");

                    b.Property<string>("EmoteMessageFormat")
                        .HasColumnType("text");

                    b.Property<string>("EmoteReactFormat")
                        .HasColumnType("text");

                    b.Property<bool>("Exclusive")
                        .HasColumnType("boolean");

                    b.HasKey("GuildId", "RoleId");

                    b.ToTable("SelfAssignAbleRoles");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.SelfAssignReactionRole", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<long>("ConfigId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Exclusive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<List<string>>("Reactions")
                        .HasColumnType("text[]");

                    b.HasKey("GuildId", "ChannelId", "MessageId");

                    b.HasIndex("ConfigId");

                    b.ToTable("SelfAssignReactionRoles");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.WelcomeBanner", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AvatarSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60);

                    b.Property<int>("AviPlaceX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<int>("AviPlaceY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<bool>("IsNsfw")
                        .HasColumnType("boolean");

                    b.Property<int>("TextPlaceX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(245);

                    b.Property<int>("TextPlaceY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(40);

                    b.Property<int>("TextSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(33);

                    b.Property<DateTimeOffset>("UploadTimeOffset")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Uploader")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("GuildId", "Id");

                    b.ToTable("WelcomeBanners");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Giveaway.Giveaway", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("AccountAgeRequirement")
                        .HasColumnType("interval");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("CloseAtOffset")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtOffset")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Creator")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("IdNum")
                        .HasColumnType("integer");

                    b.Property<int?>("LevelRequirement")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("ServerAgeRequirement")
                        .HasColumnType("interval");

                    b.Property<bool>("Stack")
                        .HasColumnType("boolean");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("WinnerAmount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Giveaways");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Giveaway.GiveawayHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ClosedAtOffset")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtOffset")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Creator")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("IdNum")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<ulong[]>("Winner")
                        .HasColumnType("numeric[]");

                    b.HasKey("Id", "GuildId");

                    b.ToTable("GiveawayHistories");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Giveaway.GiveawayParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Entry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GiveawayId")
                        .HasColumnType("uuid");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GiveawayId");

                    b.ToTable("GiveawayParticipants");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Internal.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CallSite")
                        .HasColumnType("text");

                    b.Property<string>("Exception")
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<string>("Logger")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("TimeStamp")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Moderation.ModLog", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ModId")
                        .HasColumnType("bigint");

                    b.Property<string>("Response")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id", "GuildId");

                    b.ToTable("ModLogs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Moderation.MuteTimer", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("UserId", "GuildId");

                    b.ToTable("MuteTimers");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Moderation.Report", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("Attachment")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<long?>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id", "GuildId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Moderation.Suggestion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Response")
                        .HasColumnType("text");

                    b.Property<long?>("ResponseUser")
                        .HasColumnType("bigint");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id", "GuildId");

                    b.ToTable("Suggestions");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Moderation.Warn", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Moderator")
                        .HasColumnType("numeric(20,0)");

                    b.Property<TimeSpan?>("MuteTimer")
                        .HasColumnType("interval");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Valid")
                        .HasColumnType("boolean");

                    b.HasKey("Id", "GuildId");

                    b.ToTable("Warns");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Premium.MvpConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Disabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<long?>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("GuildId");

                    b.ToTable("MvpConfigs");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Quote.Quote", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Added")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Creator")
                        .HasColumnType("bigint");

                    b.Property<int>("LevelCap")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<List<string>>("Triggers")
                        .HasColumnType("text[]");

                    b.HasKey("GuildId", "Key");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.VoiceRoles", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("VoiceId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("GuildId", "VoiceId");

                    b.ToTable("VoiceRoles");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Account.Achievement.AchievementUnlocked", b =>
                {
                    b.HasOne("Hanekawa.Database.Tables.Account.AccountGlobal", "Account")
                        .WithMany("AchievementUnlocks")
                        .HasForeignKey("AccountUserId");

                    b.HasOne("Hanekawa.Database.Tables.Account.Achievement.Achievement", "Achievement")
                        .WithMany("Unlocked")
                        .HasForeignKey("AchievementId");

                    b.Navigation("Account");

                    b.Navigation("Achievement");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Club.ClubBlacklist", b =>
                {
                    b.HasOne("Hanekawa.Database.Tables.Club.Club", "Club")
                        .WithMany("Blacklist")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Club.ClubUser", b =>
                {
                    b.HasOne("Hanekawa.Database.Tables.Club.Club", "Club")
                        .WithMany("Users")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.SelfAssignReactionRole", b =>
                {
                    b.HasOne("Hanekawa.Database.Tables.Config.Guild.ChannelConfig", "Config")
                        .WithMany("AssignReactionRoles")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Config");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Giveaway.GiveawayParticipant", b =>
                {
                    b.HasOne("Hanekawa.Database.Tables.Giveaway.Giveaway", "Giveaway")
                        .WithMany("Participants")
                        .HasForeignKey("GiveawayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Giveaway");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Account.AccountGlobal", b =>
                {
                    b.Navigation("AchievementUnlocks");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Account.Achievement.Achievement", b =>
                {
                    b.Navigation("Unlocked");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Club.Club", b =>
                {
                    b.Navigation("Blacklist");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Config.Guild.ChannelConfig", b =>
                {
                    b.Navigation("AssignReactionRoles");
                });

            modelBuilder.Entity("Hanekawa.Database.Tables.Giveaway.Giveaway", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
