// <auto-generated />
using System;
using Hanekawa.Addons.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Hanekawa.Addons.Database.Migrations
{
    [DbContext(typeof(DbService))]
    [Migration("20190119162024_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Account.Account", b =>
                {
                    b.Property<long>("GuildId");

                    b.Property<long>("UserId");

                    b.Property<bool>("Active");

                    b.Property<DateTime>("ChannelVoiceTime");

                    b.Property<int>("Class");

                    b.Property<int>("Credit");

                    b.Property<int>("CreditSpecial");

                    b.Property<DateTime>("DailyCredit");

                    b.Property<int>("Exp");

                    b.Property<DateTime?>("FirstMessage");

                    b.Property<int>("GameKillAmount");

                    b.Property<DateTime>("LastMessage");

                    b.Property<int>("Level");

                    b.Property<string>("ProfilePic");

                    b.Property<int>("Rep");

                    b.Property<DateTime>("RepCooldown");

                    b.Property<int>("Sessions");

                    b.Property<int>("StarGiven");

                    b.Property<int>("StarReceived");

                    b.Property<long>("StatMessages");

                    b.Property<TimeSpan>("StatVoiceTime");

                    b.Property<int>("TotalExp");

                    b.Property<DateTime>("VoiceExpTime");

                    b.HasKey("GuildId", "UserId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Account.AccountGlobal", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Credit");

                    b.Property<int>("Exp");

                    b.Property<int>("Level");

                    b.Property<int>("Rep");

                    b.Property<int>("StarGive");

                    b.Property<int>("StarReceive");

                    b.Property<int>("TotalExp");

                    b.HasKey("UserId");

                    b.ToTable("AccountGlobals");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Account.Inventory", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<decimal>("UserId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<int>("ItemId");

                    b.Property<int>("Amount");

                    b.HasKey("GuildId", "UserId", "ItemId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Account.InventoryGlobal", b =>
                {
                    b.Property<decimal>("UserId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<int>("ItemId");

                    b.Property<int>("Amount");

                    b.HasKey("UserId", "ItemId");

                    b.ToTable("InventoryGlobals");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Account.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("ConsumeOnUse");

                    b.Property<DateTime>("DateAdded");

                    b.Property<string>("Description");

                    b.Property<bool>("Global");

                    b.Property<decimal?>("GuildId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<string>("Name");

                    b.Property<decimal?>("Role")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<bool>("Secret");

                    b.Property<string>("SecretValue");

                    b.Property<bool>("Unique");

                    b.Property<string>("Value");

                    b.HasKey("ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Achievement.AchievementDifficulty", b =>
                {
                    b.Property<int>("DifficultyId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("DifficultyId");

                    b.ToTable("AchievementDifficulties");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Achievement.AchievementMeta", b =>
                {
                    b.Property<int>("AchievementId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AchievementNameId");

                    b.Property<string>("Description");

                    b.Property<int>("DifficultyId");

                    b.Property<bool>("Global");

                    b.Property<bool>("Hidden");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Name");

                    b.Property<bool>("Once");

                    b.Property<int>("Points");

                    b.Property<int>("Requirement");

                    b.Property<int?>("Reward");

                    b.Property<int>("TypeId");

                    b.HasKey("AchievementId");

                    b.HasIndex("AchievementNameId");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("TypeId");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Achievement.AchievementName", b =>
                {
                    b.Property<int>("AchievementNameId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<bool>("Stackable");

                    b.HasKey("AchievementNameId");

                    b.ToTable("AchievementNames");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Achievement.AchievementTracker", b =>
                {
                    b.Property<int>("Type");

                    b.Property<long>("UserId");

                    b.Property<int>("Count");

                    b.HasKey("Type", "UserId");

                    b.ToTable("AchievementTrackers");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Achievement.AchievementType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("TypeId");

                    b.ToTable("AchievementTypes");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Achievement.AchievementUnlock", b =>
                {
                    b.Property<int>("AchievementId");

                    b.Property<long>("UserId");

                    b.Property<int>("TypeId");

                    b.HasKey("AchievementId", "UserId");

                    b.ToTable("AchievementUnlocks");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Administration.Blacklist", b =>
                {
                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Reason");

                    b.Property<long>("ResponsibleUser");

                    b.Property<DateTimeOffset?>("Unban");

                    b.HasKey("GuildId");

                    b.ToTable("Blacklists");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Administration.EventSchedule", b =>
                {
                    b.Property<int>("Id");

                    b.Property<long>("GuildId");

                    b.Property<string>("Description");

                    b.Property<long?>("DesignerClaim");

                    b.Property<long>("Host");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Name");

                    b.Property<bool>("Posted");

                    b.Property<DateTime>("Time");

                    b.HasKey("Id", "GuildId");

                    b.ToTable("EventSchedules");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Administration.Patreon", b =>
                {
                    b.Property<long>("BotId");

                    b.Property<long>("UserId");

                    b.Property<DateTime>("Added");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Email");

                    b.Property<DateTime?>("Rewarded");

                    b.HasKey("BotId", "UserId");

                    b.ToTable("Patreons");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Administration.WhitelistDesign", b =>
                {
                    b.Property<long>("GuildId");

                    b.Property<long>("UserId");

                    b.HasKey("GuildId", "UserId");

                    b.ToTable("WhitelistDesigns");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Administration.WhitelistEvent", b =>
                {
                    b.Property<long>("GuildId");

                    b.Property<long>("UserId");

                    b.HasKey("GuildId", "UserId");

                    b.ToTable("WhitelistEvents");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Audio.Playlist", b =>
                {
                    b.Property<long>("GuildId");

                    b.Property<string>("Id");

                    b.Property<bool>("IsPrivate");

                    b.Property<long>("OwnerId");

                    b.Property<TimeSpan>("Playtime");

                    b.Property<int>("Streams");

                    b.HasKey("GuildId", "Id");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.BoardConfig.Board", b =>
                {
                    b.Property<long>("GuildId");

                    b.Property<long>("MessageId");

                    b.Property<DateTimeOffset?>("Boarded");

                    b.Property<int>("StarAmount");

                    b.Property<long>("UserId");

                    b.HasKey("GuildId", "MessageId");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.BotGame.GameClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ChanceAvoid");

                    b.Property<int>("ChanceCrit");

                    b.Property<long>("LevelRequirement");

                    b.Property<double>("ModifierAvoidance");

                    b.Property<double>("ModifierCriticalChance");

                    b.Property<double>("ModifierDamage");

                    b.Property<double>("ModifierHealth");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("GameClasses");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.BotGame.GameConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DefaultDamage");

                    b.Property<int>("DefaultHealth");

                    b.HasKey("Id");

                    b.ToTable("GameConfigs");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.BotGame.GameEnemy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClassId");

                    b.Property<int>("CreditGain");

                    b.Property<int>("Damage");

                    b.Property<bool>("Elite");

                    b.Property<int>("ExpGain");

                    b.Property<int>("Health");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Name");

                    b.Property<bool>("Rare");

                    b.HasKey("Id");

                    b.ToTable("GameEnemies");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Club.ClubBlacklist", b =>
                {
                    b.Property<int>("ClubId");

                    b.Property<long>("GuildId");

                    b.Property<long>("BlackListUser");

                    b.Property<long>("IssuedUser");

                    b.Property<string>("Reason");

                    b.Property<DateTimeOffset>("Time");

                    b.HasKey("ClubId", "GuildId", "BlackListUser");

                    b.ToTable("ClubBlacklists");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Club.ClubInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("GuildId");

                    b.Property<long>("Leader");

                    b.Property<long?>("AdMessage");

                    b.Property<bool>("AutoAdd");

                    b.Property<long?>("Channel");

                    b.Property<DateTimeOffset>("CreationDate");

                    b.Property<string>("Description");

                    b.Property<string>("IconUrl");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Name");

                    b.Property<bool>("Public");

                    b.Property<long?>("RoleId");

                    b.HasKey("Id", "GuildId", "Leader");

                    b.ToTable("ClubInfos");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Club.ClubPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClubId");

                    b.Property<long>("GuildId");

                    b.Property<DateTimeOffset>("JoinDate");

                    b.Property<int>("Rank");

                    b.Property<long>("UserId");

                    b.HasKey("Id", "ClubId", "GuildId");

                    b.ToTable("ClubPlayers");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.GuildConfig.EventPayout", b =>
                {
                    b.Property<long>("GuildId");

                    b.Property<long>("UserId");

                    b.Property<int>("Amount");

                    b.HasKey("GuildId", "UserId");

                    b.ToTable("EventPayouts");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.GuildConfig.GuildConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("AnimeAirChannel");

                    b.Property<bool>("AutomaticEventSchedule");

                    b.Property<long?>("BoardChannel");

                    b.Property<string>("BoardEmote");

                    b.Property<long?>("ClubAdvertisementChannel");

                    b.Property<bool>("ClubAutoPrune");

                    b.Property<long?>("ClubChannelCategory");

                    b.Property<int>("ClubChannelRequiredAmount");

                    b.Property<int>("ClubChannelRequiredLevel");

                    b.Property<bool>("ClubEnableVoiceChannel");

                    b.Property<string>("CurrencyName");

                    b.Property<string>("CurrencySign");

                    b.Property<long?>("DesignChannel");

                    b.Property<int>("EmbedColor");

                    b.Property<int?>("EmoteCountFilter");

                    b.Property<bool>("EmoteCurrency")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<long?>("EventChannel");

                    b.Property<long?>("EventSchedulerChannel");

                    b.Property<int>("ExpMultiplier");

                    b.Property<bool>("FilterAllInv");

                    b.Property<bool>("FilterInvites");

                    b.Property<int?>("FilterMsgLength");

                    b.Property<bool>("FilterUrls");

                    b.Property<bool>("IgnoreAllChannels");

                    b.Property<long?>("LogAutoMod");

                    b.Property<long?>("LogAvi");

                    b.Property<long?>("LogBan");

                    b.Property<long?>("LogJoin");

                    b.Property<long?>("LogMsg");

                    b.Property<long?>("LogWarn");

                    b.Property<int?>("MentionCountFilter");

                    b.Property<long?>("ModChannel");

                    b.Property<long?>("MusicChannel");

                    b.Property<long?>("MusicVcChannel");

                    b.Property<long?>("MuteRole");

                    b.Property<string>("Prefix");

                    b.Property<bool>("Premium")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<long?>("QuestionAndAnswerChannel");

                    b.Property<long?>("ReportChannel");

                    b.Property<string>("SpecialCurrencyName");

                    b.Property<string>("SpecialCurrencySign");

                    b.Property<bool>("SpecialEmoteCurrency")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("StackLvlRoles");

                    b.Property<long?>("SuggestionChannel");

                    b.Property<string>("SuggestionEmoteNo");

                    b.Property<string>("SuggestionEmoteYes");

                    b.Property<bool>("WelcomeBanner");

                    b.Property<long?>("WelcomeChannel");

                    b.Property<TimeSpan?>("WelcomeDelete");

                    b.Property<int>("WelcomeLimit");

                    b.Property<string>("WelcomeMessage");

                    b.HasKey("GuildId");

                    b.ToTable("GuildConfigs");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.GuildConfig.IgnoreChannel", b =>
                {
                    b.Property<long>("GuildId");

                    b.Property<long>("ChannelId");

                    b.HasKey("GuildId", "ChannelId");

                    b.ToTable("IgnoreChannels");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.GuildConfig.LevelExpEvent", b =>
                {
                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("ChannelId");

                    b.Property<long?>("MessageId");

                    b.Property<int>("Multiplier");

                    b.Property<DateTime>("Time");

                    b.HasKey("GuildId");

                    b.ToTable("LevelExpEvents");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.GuildConfig.LevelExpReduction", b =>
                {
                    b.Property<long>("GuildId");

                    b.Property<long>("ChannelId");

                    b.Property<bool>("Category");

                    b.Property<bool>("Channel");

                    b.HasKey("GuildId", "ChannelId");

                    b.ToTable("LevelExpReductions");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.GuildConfig.LevelReward", b =>
                {
                    b.Property<long>("GuildId");

                    b.Property<int>("Level");

                    b.Property<long>("Role");

                    b.Property<bool>("Stackable");

                    b.HasKey("GuildId", "Level");

                    b.ToTable("LevelRewards");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.GuildConfig.LootChannel", b =>
                {
                    b.Property<long>("GuildId");

                    b.Property<long>("ChannelId");

                    b.HasKey("GuildId", "ChannelId");

                    b.ToTable("LootChannels");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.GuildConfig.NudeServiceChannel", b =>
                {
                    b.Property<long>("GuildId");

                    b.Property<long>("ChannelId");

                    b.Property<bool>("InHouse");

                    b.Property<int>("Tolerance");

                    b.HasKey("GuildId", "ChannelId");

                    b.ToTable("NudeServiceChannels");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.GuildConfig.SelfAssignAbleRole", b =>
                {
                    b.Property<long>("GuildId");

                    b.Property<long>("RoleId");

                    b.Property<bool>("Exclusive");

                    b.HasKey("GuildId", "RoleId");

                    b.ToTable("SelfAssignAbleRoles");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.GuildConfig.SingleNudeServiceChannel", b =>
                {
                    b.Property<long>("GuildId");

                    b.Property<long>("ChannelId");

                    b.Property<bool>("InHouse");

                    b.Property<int?>("Level");

                    b.Property<int?>("Tolerance");

                    b.HasKey("GuildId", "ChannelId");

                    b.ToTable("SingleNudeServiceChannels");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.GuildConfig.SpamIgnore", b =>
                {
                    b.Property<long>("GuildId");

                    b.Property<long>("ChannelId");

                    b.HasKey("GuildId", "ChannelId");

                    b.ToTable("SpamIgnores");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.GuildConfig.UrlFilter", b =>
                {
                    b.Property<long>("GuildId");

                    b.Property<long>("ChannelId");

                    b.HasKey("GuildId", "ChannelId");

                    b.ToTable("UrlFilters");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.GuildConfig.WelcomeBanner", b =>
                {
                    b.Property<long>("GuildId");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("UploadTimeOffset");

                    b.Property<long>("Uploader");

                    b.Property<string>("Url");

                    b.HasKey("GuildId", "Id");

                    b.ToTable("WelcomeBanners");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Moderation.ModLog", b =>
                {
                    b.Property<int>("Id");

                    b.Property<long>("GuildId");

                    b.Property<string>("Action");

                    b.Property<DateTime>("Date");

                    b.Property<long>("MessageId");

                    b.Property<long?>("ModId");

                    b.Property<string>("Response");

                    b.Property<long>("UserId");

                    b.HasKey("Id", "GuildId");

                    b.ToTable("ModLogs");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Moderation.MuteTimer", b =>
                {
                    b.Property<long>("UserId");

                    b.Property<long>("GuildId");

                    b.Property<DateTime>("Time");

                    b.HasKey("UserId", "GuildId");

                    b.ToTable("MuteTimers");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Moderation.QuestionAndAnswer", b =>
                {
                    b.Property<int>("Id");

                    b.Property<long>("GuildId");

                    b.Property<DateTime>("Date");

                    b.Property<long?>("MessageId");

                    b.Property<string>("Response");

                    b.Property<long?>("ResponseUser");

                    b.Property<bool>("Status");

                    b.Property<long>("UserId");

                    b.HasKey("Id", "GuildId");

                    b.ToTable("QuestionAndAnswers");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Moderation.Report", b =>
                {
                    b.Property<int>("Id");

                    b.Property<long>("GuildId");

                    b.Property<string>("Attachment");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Message");

                    b.Property<long?>("MessageId");

                    b.Property<bool>("Status");

                    b.Property<long>("UserId");

                    b.HasKey("Id", "GuildId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Moderation.Suggestion", b =>
                {
                    b.Property<int>("Id");

                    b.Property<long>("GuildId");

                    b.Property<DateTime>("Date");

                    b.Property<long?>("MessageId");

                    b.Property<string>("Response");

                    b.Property<long?>("ResponseUser");

                    b.Property<bool>("Status");

                    b.Property<long>("UserId");

                    b.HasKey("Id", "GuildId");

                    b.ToTable("Suggestions");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Moderation.Warn", b =>
                {
                    b.Property<int>("Id");

                    b.Property<long>("GuildId");

                    b.Property<decimal>("Moderator")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<TimeSpan?>("MuteTimer");

                    b.Property<string>("Reason");

                    b.Property<DateTime>("Time");

                    b.Property<int>("Type");

                    b.Property<long>("UserId");

                    b.Property<bool>("Valid");

                    b.HasKey("Id", "GuildId");

                    b.ToTable("Warns");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Profile.Background", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BackgroundUrl");

                    b.HasKey("Id");

                    b.ToTable("Backgrounds");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Profile.ProfileConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Height");

                    b.Property<string>("Name");

                    b.Property<float>("NameWidth");

                    b.Property<string>("Value");

                    b.Property<float>("ValueWidth");

                    b.HasKey("Id");

                    b.ToTable("ProfileConfigs");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Stores.GlobalStore", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Price");

                    b.HasKey("ItemId");

                    b.ToTable("GlobalStores");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Stores.ServerStore", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<int>("ItemId");

                    b.Property<int>("Price");

                    b.Property<bool>("SpecialCredit");

                    b.HasKey("GuildId", "ItemId");

                    b.ToTable("ServerStores");
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Achievement.AchievementMeta", b =>
                {
                    b.HasOne("Hanekawa.Addons.Database.Tables.Achievement.AchievementName", "AchievementName")
                        .WithMany()
                        .HasForeignKey("AchievementNameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hanekawa.Addons.Database.Tables.Achievement.AchievementDifficulty", "AchievementDifficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hanekawa.Addons.Database.Tables.Achievement.AchievementType", "AchievementType")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hanekawa.Addons.Database.Tables.Achievement.AchievementUnlock", b =>
                {
                    b.HasOne("Hanekawa.Addons.Database.Tables.Achievement.AchievementMeta", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
